name: 'Test Ansible'

on:
  workflow_dispatch:

jobs:
  Ansible-Test:
    name: 'Ansible-Test'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform/nginx
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Copy folder to remote server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 34.66.202.16
          username: ansible
          key: ${{ secrets.ANSIBLE_KEY }}
          port: 22
          source: ./terraform/nginx
          target: /tmp/nginx
          timeout: 30s
          command_timeout: 10m
          use_insecure_cipher: false
          rm: false
          debug: false
          strip_components: 0
          overwrite: false
          tar_dereference: false
          tar_exec: tar
          proxy_port: 22
          proxy_timeout: 30s
          proxy_use_insecure_cipher: false
      - name: executing remote ssh commands using key
        uses: appleboy/ssh-action@v1.0.3
        with:
            host: 34.66.202.16
            username: ansible
            key: ${{ secrets.ANSIBLE_KEY }}
            port: 22
            script: |
              cd /tmp/nginx/terraform/nginx
              sudo apt-get install -y ansible
              ansible-playbook playbook.yml