name: 'Test Ansible'

on: [push]

jobs:
  Ansible-Test:
    name: 'Ansible-Test'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform/nginx
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: executing remote ssh commands using key
        uses: appleboy/ssh-action@v1.0.3
        with:
            host: 34.66.202.16
            username: ansible
            key: ${{ secrets.ANSIBLE_KEY }}
            port: 22
            script: |
              sudo apt-get install -y ansible
              ansible-playbook -i inventory.tpl --private-key ansible-key playbook.yml